ALTER TABLE `saludcantabriaresponde`.`user` 
DROP COLUMN `view_university`,
DROP COLUMN `view_school`,
DROP COLUMN `covid_group_residence_id`,
DROP COLUMN `covid_group_id`,
DROP COLUMN `school_id`,
DROP COLUMN `clinical_profile`,
DROP COLUMN `residence_id`,
DROP COLUMN `zone`;
