
package com.viacoreit.scs.admin.gw.https.sautentica_intranet_scsalud;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "USUARIOSPortType", targetNamespace = "https://sautentica.intranet.scsalud.es/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface USUARIOSPortType {


    /**
     * 
     * @param peticion
     * @return
     *     returns https.sautentica_intranet_scsalud.TSConecta
     */
    @WebMethod(operationName = "Conectar", action = "https://sautentica.intranet.scsalud.es/index.php#Conectar")
    @WebResult(name = "TSConecta", targetNamespace = "https://sautentica.intranet.scsalud.es/", partName = "Respuesta")
    public TSConecta conectar(
        @WebParam(name = "TEConecta", targetNamespace = "https://sautentica.intranet.scsalud.es/", partName = "Peticion")
        TEConecta peticion);

    /**
     * 
     * @param peticion
     * @return
     *     returns https.sautentica_intranet_scsalud.TSDatos
     */
    @WebMethod(operationName = "Datos", action = "https://sautentica.intranet.scsalud.es/index.php#Datos")
    @WebResult(name = "TSDatos", targetNamespace = "https://sautentica.intranet.scsalud.es/", partName = "Respuesta")
    public TSDatos datos(
        @WebParam(name = "TEDatos", targetNamespace = "https://sautentica.intranet.scsalud.es/", partName = "Peticion")
        TEDatos peticion);

}
