
package com.viacoreit.scs.admin.gw.https.sautentica_intranet_scsalud;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "USUARIOSService", targetNamespace = "https://sautentica.intranet.scsalud.es/", wsdlLocation = "file:/home/oponce/Escritorio/sanidad/cvd/wsdl_sso/sso_scs.wsdl")
public class USUARIOSService
    extends Service
{

    private static final URL USUARIOSSERVICE_WSDL_LOCATION;
    private static final WebServiceException USUARIOSSERVICE_EXCEPTION;
    private static final QName USUARIOSSERVICE_QNAME = new QName("https://sautentica.intranet.scsalud.es/", "USUARIOSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/oponce/Escritorio/sanidad/cvd/wsdl_sso/sso_scs.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USUARIOSSERVICE_WSDL_LOCATION = url;
        USUARIOSSERVICE_EXCEPTION = e;
    }

    public USUARIOSService() {
        super(__getWsdlLocation(), USUARIOSSERVICE_QNAME);
    }

    public USUARIOSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USUARIOSSERVICE_QNAME, features);
    }

    public USUARIOSService(URL wsdlLocation) {
        super(wsdlLocation, USUARIOSSERVICE_QNAME);
    }

    public USUARIOSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USUARIOSSERVICE_QNAME, features);
    }

    public USUARIOSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public USUARIOSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns USUARIOSPortType
     */
    @WebEndpoint(name = "USUARIOSPort")
    public USUARIOSPortType getUSUARIOSPort() {
        return super.getPort(new QName("https://sautentica.intranet.scsalud.es/", "USUARIOSPort"), USUARIOSPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns USUARIOSPortType
     */
    @WebEndpoint(name = "USUARIOSPort")
    public USUARIOSPortType getUSUARIOSPort(WebServiceFeature... features) {
        return super.getPort(new QName("https://sautentica.intranet.scsalud.es/", "USUARIOSPort"), USUARIOSPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USUARIOSSERVICE_EXCEPTION!= null) {
            throw USUARIOSSERVICE_EXCEPTION;
        }
        return USUARIOSSERVICE_WSDL_LOCATION;
    }

}
